config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static#index'

  resources :users, only: [:show, :index] do
    resources :images
  end

end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :photo

 validates :photo_file_name, :presence => true
 validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
 validates :description, :presence => true

 belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username
  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # def after_sign_in_path_for(resource)
  #   sign_in_url = new_user_session_url
  #   if request.referer == sign_in_url
  #     super
  #   else
  #     stored_location_for(resource) || request.referer || root_path
  #   end
  # end


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :password) }
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  before_action :authenticate_user!

  def new
    @user = User.find(params[:user_id])
    @image = @user.images.new
  end

  def create
    @user = User.find(params[:user_id])
    @image = @user.images.new(image_params)
    if @image.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @image = Image.find(params[:id])
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      redirect_to user_path(@image.user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to user_path(@user)
  end

  private

  def image_params
    params.require(:image).permit(:photo, :description)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    @users = User.all
    @images = Image.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.erb
<%= form_for [@user, @image], html: { multipart: true } do |f| %>
  <%= f.label :photo %>
  <%= f.file_field :photo %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit "Save" %>
<% end %>

app/views/images/edit.html.erb
<%= render 'form' %>

app/views/images/new.html.erb
<h1>Image Form</h1>

<%= form_for [@user, @image], html: { multipart: true } do |f| %>
  <%= f.label :photo %>
  <%= f.file_field :photo %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit "Upload" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flakr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> |
        <%= link_to "Login", new_user_session_path %>
      <% end %>

    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%# flash.each do |name, msg| %>
      <%# content_tag :div, msg, id: "flash_#{name}" %>
    <%# end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/users/index.html.erb
<h1>Hello?</h1>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %></h1>


<ul>
  <% @user.images.each do |image| %>
  <li><%= image_tag(image.photo) %><%= image.description %>
  <%  if current_user == @user %>
  <%= link_to "Edit", edit_user_image_path(@user, image) %>
  <%= link_to "Delete", user_image_path(@user, image), :method => 'delete' %>
  <% end %>
  </li>
  <% end %>
</ul>

<%= link_to "Add an image", new_user_image_path(@user) %>